<div class="collapse navbar-collapse" id="blog-top-menu">
    <ul class="nav navbar-nav">
        <li class="active">
            <a href="#">Home</a>
			
        </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        <li>
            <?php if ($this->session->get('identity')): ?>
                <a href="#">Sign Out</a>
            <?php else: ?>
                <a href="#">Sign In</a>
            <?php endif; ?>
        </li>
    </ul>
</div>
